#Adapted from https://github.com/beark/ftl/blob/master/.travis.yml Copyright (c) 2013 Björn Aili modified by John Bandela
language: cpp
compiler:
  - gcc

# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

# Install dependencies
install:
  # install g++ 4.8, if tests are run with g++
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

  # install clang-3.4 if CPP14==1
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4 

  - cwd=$(pwd)

  # Install libc++ if tests are run with clang++
  - svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk@201601 libcxx

  - cd libcxx/lib && bash buildit
  - sudo cp ./libc++.so.1.0 /usr/lib/
  - sudo mkdir /usr/include/c++/v1
  - cd .. && sudo cp -r include/* /usr/include/c++/v1/
  - cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so
  - sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd
  - sudo cp /usr/include/c++/v1/cxxabi.h /usr/include


# command to run tests
script: 
  - cd testing/test
  - ./test.sh libc++
