#Adapted from https://github.com/beark/ftl/blob/master/.travis.yml Copyright (c) 2013 Björn Aili modified by John Bandela
language: cpp
compiler:
  - gcc

# Setup repos etc before installation
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq

# Install dependencies
install:
  # install g++ 4.8, if tests are run with g++
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

  # install clang-3.4 if CPP14==1
  - sudo apt-get install --allow-unauthenticated -qq clang-3.4 

  - cwd=$(pwd)

  # Install libc++ if tests are run with clang++

  - svn co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - mkdir build_libcxx && cd build_libcxx
  - CC=clang CXX=clang++ cmake -G "Unix Makefiles" -DLIBCXX_CXX_ABI=libsupc++ -DLIBCXX_LIBSUPCXX_INCLUDE_PATHS="/usr/include/c++/4.8/;/usr/include/c++/4.8/x86_64-linux-gnu/;/usr/include/x86_64-linux-gnu/c++/4.8/" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../libcxx
  - make -j 8
  - sudo make install



# command to run tests
script: 
  - cd testing/test
  - ./test.sh libc++
